name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: Jobbo
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission
        run: chmod +x gradlew

      - name: Ktlint Check
        run: ./gradlew ktlintCheck

      - name: Build
        run: ./gradlew build -x test

      - name: Test
        env:
          DB_URL: jdbc:postgresql://localhost:5432/Jobbo
          DB_USERNAME: postgres
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: ./gradlew test